name: coherence
dependencies:
- openssl=1.0.2k=0
- pip=9.0.1=py27_1
- python=2.7.13=0
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pip:
  - flask==0.12
  - flask-cors==3.0.2
  - flask-sqlalchemy==2.1
  - gevent==1.2.1
  - gunicorn
  - six==1.10.0
